apiVersion: v1
kind: Pod
metadata:
  name: fluent-bit
spec:
  containers:
  - image: fluent/fluent-bit:0.11.6
    name: fluent-bit
    tty: true
    volumeMounts:
    - mountPath: /var/log/
      name: node-var-log
      readOnly: true
    - mountPath: /mnt/sda1/var/lib/docker/
      name: node-var-lib-docker
      readOnly: true
    - mountPath: /fluent-bit/etc/
      name: fluent-bit-config
  - image: larskumbier/fluentd
    name: fluentd
    tty: true
    ports:
    - containerPort: 24224
    volumeMounts:
    - mountPath: /fluentd/etc/
      name: fluentd-config
  volumes:
  ## General node information, kubernetes-logs, azure init, etc.
  - name: node-var-log
    hostPath:
      path: /var/log
  ## Logging from containers
  - name: node-var-lib-docker
    hostPath:
      path: /mnt/sda1/var/lib/docker
  - name: fluent-bit-config
    configMap:
      name: fluent-bit
  - name: fluentd-config
    configMap:
      name: fluentd